### ISSUE TITLE
Tags ### not interpreted

### ISSUE THREAD

**Issue by stakepoolplace** [cstayyab/markdown-to-unicode#1]
markdown tags ### are not interpreted

**Comment by cstayyab** [comment]
@stakepoolplace this is not currently in the roadmap but I will definitely look into it once all things in current roadmap are accomplished. You can view current Roadmap here: https://github.com/cstayyab/markdown-to-unicode?tab=readme-ov-file#roadmap

PS: PRs are always welcome.
